backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "site"
    label: "Contenu du site"
    files:
      - label: "Données principales"
        name: "content"
        file: "content/site.json"
        format: "json"
        fields:
          - { label: "Titre principal", name: "hero_title", widget: "string" }
          - { label: "Sous-titre", name: "hero_subtitle", widget: "string" }
          - { label: "Texte du bouton", name: "cta_text", widget: "string", default: "Nous contacter" }
          - { label: "Lien du bouton", name: "cta_link", widget: "string", default: "#contact" }
          - { label: "Logo (URL)", name: "logo", widget: "string", required: false, hint: "Ex: images/uploads/logo.png" }
          - label: "Menu"
            name: "menu_items"
            widget: "list"
            fields:
              - { label: "Nom du plat", name: "name", widget: "string" }
              - { label: "Prix", name: "price", widget: "string", required: false }
          - { label: "Horaires", name: "hours", widget: "text" }
          - { label: "Adresse", name: "address", widget: "string" }
          - { label: "Téléphone", name: "phone", widget: "string" }
          - { label: "Carte (iframe)", name: "map_iframe", widget: "text", required: false, hint: "Collez l'iframe Google Maps" }
